@include('administrator.layouts.head')
@include('administrator.layouts.header')
@include('administrator.layouts.sidebar')
@include('administrator.layouts.content')
@include('administrator.layouts.footer')